import Head from 'next/head'
import HeroSection from '../components/HeroSection'
import ProductSection from '../components/ProductSection'

import axios from 'axios'



export default function Home({ products }) {
  return (
    <div className="pt-14 md:pt-24">
      <Head>
        <title>ProShop || buy all you need</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HeroSection/>
      <ProductSection products={products} />

   
    </div>
  )
}


export async function getServerSideProps(context) {

  const request = await axios.get(`${process.env.DOMAIN_NAME}/api/getproducts`)
  const {products} = request.data
  return {
    props: {products}, // will be passed to the page component as props
  }
}


